spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
    # TODO: URIs were supposed to work with lb:// prefix, it seems to be failing,
    # at leastwhen deployed to a non-default namespace
  cloud:
    gateway:
      routes:
        - id: vets-service
          uri: http://vets-service:8083
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: http://visits-service:8082
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: http://customers-service:8081
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
        # - id: gateway-owners-service
        #   uri: http://customers-service:8080
        #   predicates:
        #     - Path=/api/gateway/owners/**
        #   filters:
        #     - StripPrefix=2
        # - id: owners-service
        #   uri: http://customers-service:8080
        #   predicates:
        #     - Path=/api/owners/**
        #   filters:
        #     - StripPrefix=1
