apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: pet-clinic
  labels:
    app: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
      - image: "$CONTAINER_IMAGE"
        name: prometheus-server
        env:
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: config-server
              key: CONFIG_SERVER_URL
        - name: ENVIRONMENT
          value: AKS
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/healthy
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/ready
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 30
          successThreshold: 1
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
        securityContext:
          privileged: false

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-server
  name: prometheus-server
  namespace: pet-clinic
spec:
  ports:
  - port: 9091
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus-server
  type: ClusterIP
