apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customers-service
  name: customers-service
  namespace: pet-clinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: pet-clinic-custs-service-account
      containers:
      - image: "$CONTAINER_IMAGE"
        name: customers-service
        env:
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: config-server
              key: CONFIG_SERVER_URL
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: kv-secrets-pet-clinic-custs-svc
              key: APP-INSIGHTS-CONNECTION-STRING
              optional: false
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            secretKeyRef:
              name: kv-secrets-pet-clinic-custs-svc
              key: APP-INSIGHTS-INSTRUMENTATION-KEY
              optional: false
        - name: APPLICATIONINSIGHTS_CONFIGURATION_CONTENT
          value: >-
            {
                "role": {
                    "name": "customers-service"
                  }
            }
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: kv-secrets-pet-clinic-custs-svc
              key: SPRING-DATASOURCE-URL
              optional: false
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: kv-secrets-pet-clinic-custs-svc
              key: SPRING-DS-USER
              optional: false
        - name: SPRING_DATASOURCE_SHOW_SQL
          valueFrom:
            configMapKeyRef:
              name: config-server
              key: SPRING_DATASOURCE_SHOW_SQL
        - name: ENVIRONMENT
          value: AKS
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          successThreshold: 1
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        securityContext:
          privileged: false
        volumeMounts:
          - name: secrets-store01-inline
            mountPath: /mnt/secrets-store
            readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi: 
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: kv-secrets-pet-clinic-custs-svc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: customers-service
  name: customers-service
  namespace: pet-clinic
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: customers-service
  type: ClusterIP
