apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: todo-edit
  namespace: todo
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: "$TODO_APP_EDIT_AD_GROUP_ID"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: todo-view
  namespace: todo
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: "$TODO_APP_VIEW_AD_GROUP_ID"
  apiGroup: rbac.authorization.k8s.io
