apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pet-clinic-edit
  namespace: pet-clinic
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: "$PET_CLINIC_APP_EDIT_AD_GROUP_ID"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pet-clinic-view
  namespace: pet-clinic
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: "$PET_CLINIC_APP_VIEW_AD_GROUP_ID"
  apiGroup: rbac.authorization.k8s.io
