apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets-todo-app
  namespace: todo
spec:
  provider: azure
  secretObjects:
  - secretName: kv-secrets-todo-app
    type: Opaque
    data:
      - objectName: TODO-SPRING-DATASOURCE-URL
        key: TODO-SPRING-DATASOURCE-URL
      - objectName: TODO-SPRING-DATASOURCE-USERNAME
        key: TODO-SPRING-DATASOURCE-USERNAME
      - objectName: TODO-APP-INSIGHTS-CONNECTION-STRING # References connection string below
        key: TODO-APP-INSIGHTS-CONNECTION-STRING # Key within k8s secret for this value
      - objectName: TODO-APP-INSIGHTS-INSTRUMENTATION-KEY
        key: TODO-APP-INSIGHTS-INSTRUMENTATION-KEY
  parameters:
    usePodIdentity: "false"
    keyvaultName: "$KEYVAULT_NAME"
    clientID: "$TODO_APP_CLIENT_ID"
    objects:  |
      array:
        - |
          objectName: TODO-SPRING-DATASOURCE-URL
          objectAlias: TODO-SPRING-DATASOURCE-URL
          objectType: secret
        - |
          objectName: TODO-SPRING-DATASOURCE-USERNAME
          objectAlias: TODO-SPRING-DATASOURCE-USERNAME
          objectType: secret
        - |
          objectName: TODO-APP-INSIGHTS-CONNECTION-STRING
          objectAlias: TODO-APP-INSIGHTS-CONNECTION-STRING
          objectType: secret
        - |
          objectName: TODO-APP-INSIGHTS-INSTRUMENTATION-KEY
          objectAlias: TODO-APP-INSIGHTS-INSTRUMENTATION-KEY
          objectType: secret
    tenantId: "$TENANT_ID"
