apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets-pet-clinic-app
  namespace: pet-clinic
spec:
  provider: azure
  secretObjects:
    - secretName: kv-secrets-pet-clinic-app
      type: Opaque
      data:
        - key: APP-INSIGHTS-CONNECTION-STRING
          objectName: PET-CLINIC-APP-INSIGHTS-CONNECTION-STRING
        - key: APP-INSIGHTS-INSTRUMENTATION-KEY
          objectName: PET-CLINIC-APP-INSIGHTS-INSTRUMENTATION-KEY
  parameters:
    usePodIdentity: "false"
    keyvaultName: "$KEYVAULT_NAME"
    clientID: "$PET_CLINIC_APP_CLIENT_ID"
    objects:  |
      array:
        - |
          objectName: PET-CLINIC-APP-INSIGHTS-CONNECTION-STRING
          objectAlias: PET-CLINIC-APP-INSIGHTS-CONNECTION-STRING
          objectType: secret
        - |
          objectName: PET-CLINIC-APP-INSIGHTS-INSTRUMENTATION-KEY
          objectAlias: PET-CLINIC-APP-INSIGHTS-INSTRUMENTATION-KEY
          objectType: secret
    tenantId: "$TENANT_ID"
