apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets-pet-clinic-config-svc
  namespace: pet-clinic
spec:
  provider: azure
  secretObjects:
    - secretName: kv-secrets-pet-clinic-config-svc
      type: Opaque
      data:
        - key: GIT-REPO-URI # data field to populate
          objectName: PET-CLINIC-CONFIG-SVC-GIT-REPO-URI # name of the mounted content to sync; this could be the object name or the object alias
        - key: GIT-REPO-USERNAME
          objectName: PET-CLINIC-CONFIG-SVC-GIT-REPO-USERNAME
        - key: GIT-REPO-PASSWORD
          objectName: PET-CLINIC-CONFIG-SVC-GIT-REPO-PASSWORD
        - key: APP-INSIGHTS-CONNECTION-STRING
          objectName: PET-CLINIC-APP-INSIGHTS-CONNECTION-STRING
        - key: APP-INSIGHTS-INSTRUMENTATION-KEY
          objectName: PET-CLINIC-APP-INSIGHTS-INSTRUMENTATION-KEY 
  parameters:
    usePodIdentity: "false"
    keyvaultName: "$KEYVAULT_NAME"
    clientID: "$CONFIG_SVC_CLIENT_ID"
    objects:  |
      array:
        - |
          objectName: PET-CLINIC-CONFIG-SVC-GIT-REPO-URI
          objectAlias: PET-CLINIC-CONFIG-SVC-GIT-REPO-URI
          objectType: secret
        - |
          objectName: PET-CLINIC-CONFIG-SVC-GIT-REPO-USERNAME
          objectAlias: PET-CLINIC-CONFIG-SVC-GIT-REPO-USERNAME
          objectType: secret
        - |
          objectName: PET-CLINIC-CONFIG-SVC-GIT-REPO-PASSWORD
          objectAlias: PET-CLINIC-CONFIG-SVC-GIT-REPO-PASSWORD
          objectType: secret
        - |
          objectName: PET-CLINIC-APP-INSIGHTS-CONNECTION-STRING
          objectAlias: PET-CLINIC-APP-INSIGHTS-CONNECTION-STRING
          objectType: secret
        - |
          objectName: PET-CLINIC-APP-INSIGHTS-INSTRUMENTATION-KEY
          objectAlias: PET-CLINIC-APP-INSIGHTS-INSTRUMENTATION-KEY
          objectType: secret
    tenantId: "$TENANT_ID"
