apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
  namespace: todo
  labels:
    deploy: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: todo-app-service-account
      containers:
      - image: "$CONTAINER_IMAGE"
        imagePullPolicy: Always
        name: todoapp
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.3"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        env:
        - name: PORT
          value: "80"
        - name: LOAD_DEMO_DATA
          value: "TRUE"
        - name: SPRING_PROFILES_ACTIVE
          value: "azure"
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: kv-secrets-todo-app
              key: TODO-APP-INSIGHTS-CONNECTION-STRING
              optional: false
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            secretKeyRef:
              name: kv-secrets-todo-app
              key: TODO-APP-INSIGHTS-INSTRUMENTATION-KEY
              optional: false
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: kv-secrets-todo-app
              key: TODO-SPRING-DATASOURCE-URL
              optional: false
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: kv-secrets-todo-app
              key: TODO-SPRING-DATASOURCE-USERNAME
              optional: false
        - name: SPRING_DATASOURCE_SHOW_SQL
          valueFrom:
            configMapKeyRef:
              name: config-server
              key: SPRING_DATASOURCE_SHOW_SQL              
        - name: ENVIRONMENT
          value: AKS
        volumeMounts:
          - name: secrets-store01-inline
            mountPath: /mnt/secrets-store
            readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi: 
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: kv-secrets-todo-app

---

apiVersion: v1
kind: Service
metadata:
  name: todoapp
  namespace: todo
spec:
  selector:
    app: todoapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todoapp
  namespace: todo
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: appGatewaySslCertToDo
    appgw.ingress.kubernetes.io/request-timeout: "90"
    appgw.ingress.kubernetes.io/cookie-based-affinity: "true"
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: $HOST_NAME
    http:
      paths:
      - path: /
        backend:
          service:
            name: todoapp
            port:
              number: 80
        pathType: Exact

########################################################################
# AGIC as an add-on - service needs to run in the default namespace
# and so the pod needs to be in the default namespace too
########################################################################
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: todoapp
#spec:
#  ports:
#  - protocol: TCP
#    port: 80
#    targetPort: 80
#  selector:
#    app: todoapp
#  type: ClusterIP
#
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: todoapp
#spec:
#  ingressClassName: azure-application-gateway
#  rules:
#  - http:
#      paths:
#      - path: /
#        backend:
#          service:
#            name: todoapp
#            port:
#              number: 80
#        pathType: Exact