CREATE SEQUENCE IF NOT EXISTS visits_id_seq
  INCREMENT BY 1
  START WITH 5
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1;

CREATE TABLE IF NOT EXISTS visits (
  "id" INT PRIMARY KEY NOT NULL DEFAULT nextval('visits_id_seq'),
  "pet_id" INT NOT NULL,
  "visit_date" TIMESTAMP,
  "description" VARCHAR(8192),
  FOREIGN KEY ("pet_id") REFERENCES pets("id")
);
