name: 99-test-agic

on:
  workflow_dispatch:

jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    env:
      AKS_NAME: ${{secrets.AKS_NAME}}
      AKS_SUBSCRIPTION_ID: ${{secrets.AKS_SUBSCRIPTION_ID}}
      AKS_RESOURCE_GROUP: ${{secrets.AKS_RESOURCE_GROUP}}
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure login in AKS Subscription # https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure
        uses: azure/login@v2
        with:
          client-id: "${{secrets.AAD_CLIENT_ID}}"
          tenant-id: "${{secrets.AAD_TENANT_ID}}"
          subscription-id: "${{env.AKS_SUBSCRIPTION_ID}}"

      - name: Download ASPNETAPP demo workload
        run: |
          curl https://raw.githubusercontent.com/Azure/application-gateway-kubernetes-ingress/master/docs/examples/aspnetapp.yaml -o aspnetapp.yaml
          echo "aspnetapp.yaml:"
          echo "---------------"
          cat aspnetapp.yaml

      - name: Apply ASPNETAPP workload YAML
        run: |
          az aks command invoke \
              --resource-group ${{env.AKS_RESOURCE_GROUP}} \
              --name ${{env.AKS_NAME}} \
              --command "kubectl apply -f aspnetapp.yaml" \
              --file aspnetapp.yaml
